name: TribesNextDoor
main: me.theguynextdoor.tribesnextdoor.TribesNextDoor
author: theguynextdoor
version: 1.4.1
softdepend: [Vault]
commands:
    tribe:
        description: tribes main command
        usage: /<command>
        aliases: [t]
    resident:
        description: resident command
        usage: /<command>
        aliases: [res]
    tribechat:
        description: tribe chat command
        usage: /<command> <message>
        aliases: [tc]
    ttp:
        description: teleport to tribe members
        usage: /<command> <target>
    civilisation:
        description: civilisation command
        usage: /<command>
        aliases: [civ]
    civilisationchat:
        description: civilisation chat command
        usage: /<command>
        aliases: [cc]
    tribeadmin:
        description: admin command
        usage: /<command>
        aliases: [ta]